on:
    push:
      branches:
        - main
  
jobs:
    deploy:
      name: Deploy Dev
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
          with:
            persist-credentials: false
  
        - name: Copy repository to SSH server
          uses: appleboy/scp-action@master
          with:
              host: ${{ secrets.SSH_HOST }}
              username:  ${{ secrets.SSH_USERNAME }}
              key: ${{ secrets.SSH_KEY }}
              port: ${{ secrets.SSH_PORT }}
              source: .
              target: /home/${{ secrets.SSH_USERNAME }}/deploy/boatstuff.pro/frontend/

        - name: Prepare
          uses: appleboy/ssh-action@master
          with:
            host: ${{ secrets.SSH_HOST }}
            username: ${{ secrets.SSH_USERNAME }}
            port: ${{ secrets.SSH_PORT }}
            key: ${{ secrets.SSH_KEY }}
            script: |
              cd /home/${{ secrets.SSH_USERNAME }}/deploy/boatstuff.pro/frontend/ &&
              npm install && 
              npm run build &&
              pm2 restart frontend
  